# drone 构建
kind: pipeline
type: docker
name: vueapp

# drone构建步骤
# 无拷贝到本地流程
steps:
  # 1.构建
  - name: build
    pull: if-not-exists
    image: schaumtier/dotnetcore-sonar-node
    commands:
      # 开始构建
      - dotnet publish -o app
      - echo 项目生成成功
   
  # 2.推送 docker hub
  - name: publish
    pull: if-not-exists
    image: plugins/docker
    settings:
      username:
        from_secret: dockerhub_username
      password:
        from_secret: dockerhub_password
      repo: dkww/vueapp
      dockerfile: Dockerfile
      tags:
      - 1.0.0
      - 1.0


# drone执行触发器
trigger:
  branch:
    - master