# drone 构建
kind: pipeline
type: docker
name: vueapp

# drone构建步骤
# 无拷贝到本地流程
steps:
  # 1..NET 构建
  - name: .net build
    pull: if-not-exists
    image: mcr.microsoft.com/dotnet/core/sdk:3.1
    commands:
      # 开始构建
      - dotnet restore
      - dotnet build -c Release
      - echo 项目生成成功

  # 2.node 构建
  - name: vue build
    pull: if-not-exists
    image: node:latest
    commands:
      # 开始构建
      - cd src/vueapp/clientapp
      - npm install
      - npm run build


# drone执行触发器
trigger:
  branch:
    - master