# drone 构建
kind: pipeline
type: docker
name: vueapp

# drone构建步骤
# 无拷贝到本地流程
steps:
  # 1..NET 构建
  - name: .net build
    pull: if-not-exists
    image: mcr.microsoft.com/dotnet/core/sdk:3.1
    commands:
      # 开始构建
      - dotnet restore
      - dotnet build -c Release
      - echo 项目生成成功

  # 2.node 构建
  - name: vue build
    pull: if-not-exists
    image: node:latest
    commands:
      # 开始构建
      - ls
      - ls src/vueapp/bin/Release/netcoreapp3.1
      - cd src/vueapp/clientapp
      - npm install
      - npm run build
      - pwd
      - cp -r dist src/vueapp/bin/Release/netcoreapp3.1/clientapp

   
  # 3.推送 docker hub
  - name: publish
    pull: if-not-exists
    image: plugins/docker
    settings:
      username:
        from_secret: dockerhub_username
      password:
        from_secret: dockerhub_password
      repo: dkww/vueapp
      dockerfile: Dockerfile
      tags:
      - 1.0.0
      - 1.0


# drone执行触发器
trigger:
  branch:
    - master